# Generated by Django 3.1.6 on 2021-03-10 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatures',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specifications.featurevalidator', verbose_name='Значение'),
        ),
    ]
