# Generated by Django 3.1.6 on 2021-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specifications', '0002_auto_20210310_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatures',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.DeleteModel(
            name='FeatureValidator',
        ),
    ]
