# Generated by Django 3.1.6 on 2021-03-10 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('specifications', '0003_auto_20210310_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeatures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='shop.product', verbose_name='Товар'),
        ),
    ]
